---
name: Linting

on:
  pull_request:

jobs:
  asciidoc:
    name: 'Build AsciiDocs'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Build each .adoc with Asciidoctor, fail on WARN or above
        run: |
          FAILED=0
          if ! docker run --rm -v $(pwd):/rhacm-docs/ asciidoctor/docker-asciidoctor@sha256:59a7e165ed6375dd5dfb930cb90019f1ccaee39787dc97a3918d7022a7503543 find /rhacm-docs/ -name \*.adoc -exec asciidoctor --failure-level WARN --trace --verbose --warnings {} +; then
            echo "Build errors were detected, see per-file details above."
            exit 1
          fi
